Update CI_Pipeline.yml

diff --git a/.github/workflows/CI_Pipeline.yml b/.github/workflows/CI_Pipeline.yml
--- a/.github/workflows/CI_Pipeline.yml
+++ b/.github/workflows/CI_Pipeline.yml
@@ -101,3 +101,10 @@ jobs:
       - name: Run JUnit tests
         working-directory: backend
         run: mvn test
+
+      - name: Print test failure report
+        if: failure()  # Only runs if previous step failed
+        run: |
+          echo "Printing Surefire test logs:"
+          cat backend/target/surefire-reports/*.txt || true
+
